name: Code Review with ChatGPT

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  codereview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install requests

      - name: Run ChatGPT review
        run: |
          source env/bin/activate
          python chatgpt_review.py ${{ github.event.pull_request.number }} ${GITHUB_TOKEN} ${CHATGPT_API_TOKEN}
