name: Review Code with ChatGPT

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Call ChatGPT for code review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          # Get PR number and branch
          pr_number=$(echo "$GITHUB_REF" | cut -d / -f 3)
          pr_branch="pr-$pr_number"
    
          # Create a new branch to avoid conflicts
          git checkout -b $pr_branch
          git merge $GITHUB_SHA
    
          # Get the last commit SHA and check it out
          last_commit=$(git rev-parse HEAD)
          git checkout $last_commit
    
          # Call ChatGPT for review
          review=$(python3 chatgpt.py -c $pr_branch -f diff)
    
          # Post a comment on the PR with the review
          curl -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\": \"$review\"}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$pr_number/comments"
